/**
 * Interactive `buggy init` wizard.
 *
 * Generating a one-size-fits-all `.debugger.yaml` forced every user to hand-edit
 * the file before the tool worked at all — most importantly `language`, which
 * selects both the Tree-sitter grammar and the execution runtime. Getting it
 * wrong silently parses Python with the TypeScript grammar and finds nothing.
 *
 * This module detects sensible defaults from the project itself, asks a short set
 * of questions, and writes a config tailored to the answers. Every prompt has a
 * default, so the whole wizard can be skipped with `--yes`, driven by flags, or
 * bypassed automatically in a non-interactive shell (CI, piped stdin).
 *
 * @module config/init-wizard
 */

import { createInterface } from 'node:readline/promises';
import { readdirSync, existsSync, readFileSync, appendFileSync, writeFileSync } from 'node:fs';
import type { Dirent } from 'node:fs';
import { join, extname } from 'node:path';

/** Languages the wizard can configure. */
export type InitLanguage = 'typescript' | 'javascript' | 'python';

/** How hard the prover should search before giving up. */
export interface SearchPreset {
  name: string;
  search_budget: number;
  max_refinement_iterations: number;
}

/** Named search presets, from fastest to most thorough. */
export const SEARCH_PRESETS: Record<'quick' | 'balanced' | 'thorough', SearchPreset> = {
  quick: { name: 'quick', search_budget: 30, max_refinement_iterations: 3 },
  balanced: { name: 'balanced', search_budget: 100, max_refinement_iterations: 10 },
  thorough: { name: 'thorough', search_budget: 300, max_refinement_iterations: 20 },
};

/** The full set of decisions needed to write a config. */
export interface InitAnswers {
  language: InitLanguage;
  preset: SearchPreset;
  timeoutSeconds: number;
  watchlistScope: 'local' | 'team' | 'global' | 'layered';
  updateGitignore: boolean;
}

/** Directories never worth scanning when detecting the project language. */
const IGNORED_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', 'out', 'coverage',
  'venv', '.venv', 'env', '__pycache__', '.debugger', '.kiro', '.idea', '.vscode',
]);

/** Cap on files inspected during detection, so init stays fast on large repos. */
const DETECTION_FILE_LIMIT = 2000;

/**
 * Guess the project's primary language by counting source files.
 *
 * @param projectRoot - Directory to scan.
 * @returns The most common supported language, or null when nothing is found.
 */
export function detectLanguage(projectRoot: string): InitLanguage | null {
  const counts: Record<InitLanguage, number> = { typescript: 0, javascript: 0, python: 0 };
  let seen = 0;

  const walk = (dir: string, depth: number): void => {
    if (depth > 6 || seen >= DETECTION_FILE_LIMIT) return;

    let entries: Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true, encoding: 'utf-8' });
    } catch {
      return; // unreadable directory — skip rather than fail init
    }

    for (const entry of entries) {
      if (seen >= DETECTION_FILE_LIMIT) return;

      if (entry.isDirectory()) {
        if (!IGNORED_DIRS.has(entry.name) && !entry.name.startsWith('.')) {
          walk(join(dir, entry.name), depth + 1);
        }
        continue;
      }

      seen++;
      switch (extname(entry.name).toLowerCase()) {
        case '.ts':
        case '.tsx':
          counts.typescript++;
          break;
        case '.js':
        case '.jsx':
        case '.mjs':
        case '.cjs':
          counts.javascript++;
          break;
        case '.py':
          counts.python++;
          break;
      }
    }
  };

  walk(projectRoot, 0);

  const ranked = (Object.keys(counts) as InitLanguage[])
    .map((lang) => ({ lang, count: counts[lang] }))
    .sort((a, b) => b.count - a.count);

  const top = ranked[0];
  return top && top.count > 0 ? top.lang : null;
}

/** Per-language parser / LSP / runtime settings. */
function languageSettings(language: InitLanguage): {
  parser: string;
  lsp: string;
  runtime: string;
} {
  if (language === 'python') {
    return { parser: 'tree-sitter-python', lsp: 'pylsp', runtime: 'python' };
  }
  // The bundled TypeScript grammar parses JavaScript too.
  return { parser: 'tree-sitter-typescript', lsp: 'typescript-language-server', runtime: 'node' };
}

/**
 * Render a `.debugger.yaml` for the given answers.
 *
 * Only keys the config loader recognizes are emitted, so loading the generated
 * file produces no warnings.
 *
 * @param answers - Resolved wizard answers.
 */
export function buildConfigYaml(answers: InitAnswers): string {
  const { parser, lsp, runtime } = languageSettings(answers.language);

  return `# Buggy Configuration
# Generated by: buggy init
#
# Regenerate at any time with: buggy init --force

# Selects BOTH the Tree-sitter grammar and the execution runtime used to prove
# bugs. Change this if the project's primary language changes.
language: ${answers.language}

parser:
  command: ${parser}
  # grammar_path: ./path/to/custom-grammar.wasm

lsp:
  command: ${lsp}
  # initialization_options: {}

sandbox:
  runtime: ${runtime}
  memory_limit_mb: 512
  timeout_seconds: ${answers.timeoutSeconds}
  egress_policy: deny

oracles:
  # A function running longer than this is reported as a hang (catches infinite loops).
  timeout_threshold_seconds: 10
  crash_detection: true
  overflow_detection: true
  determinism_check_count: 5

probe:
  # "${answers.preset.name}" preset — raise search_budget to find more bugs, at the
  # cost of a longer run.
  search_budget: ${answers.preset.search_budget}
  max_refinement_iterations: ${answers.preset.max_refinement_iterations}

watchlist:
  enabled: true
  # local  = private to you (.debugger/, git-ignored)
  # team   = committed lessons in .kiro/steering/ (shared with the repo)
  # global = reused across all your projects (sanitized)
  # layered = all of the above
  scope: ${answers.watchlistScope}

# plugs:
#   parsing: ./plugs/my-parser
#   oracles: ["./plugs/custom-oracle"]
#   repair: ./plugs/my-repair-strategy
#   sandbox_executor: ./plugs/my-sandbox
`;
}

/** Defaults used for `--yes` and non-interactive runs. */
export function defaultAnswers(detected: InitLanguage | null): InitAnswers {
  return {
    language: detected ?? 'typescript',
    preset: SEARCH_PRESETS.balanced,
    timeoutSeconds: 60,
    watchlistScope: 'layered',
    updateGitignore: true,
  };
}

/** Options controlling how the wizard collects answers. */
export interface WizardOptions {
  /** When false, defaults are used without prompting. */
  interactive: boolean;
  /** Pre-answer the language question (from `--language`). */
  languageOverride?: string;
}

/** Normalize a user-supplied language string. */
export function normalizeLanguage(value: string): InitLanguage | null {
  const v = value.toLowerCase().trim();
  if (v === 'python' || v === 'py') return 'python';
  if (v === 'typescript' || v === 'ts') return 'typescript';
  if (v === 'javascript' || v === 'js') return 'javascript';
  return null;
}

/**
 * Collect init answers, prompting only when running interactively.
 *
 * @param projectRoot - Project directory, used for language detection.
 * @param options - Interactivity and flag overrides.
 */
export async function collectAnswers(
  projectRoot: string,
  options: WizardOptions
): Promise<InitAnswers> {
  const detected = detectLanguage(projectRoot);
  const answers = defaultAnswers(detected);

  // An explicit flag always wins, and is honored in both modes.
  if (options.languageOverride) {
    const override = normalizeLanguage(options.languageOverride);
    if (!override) {
      throw new Error(
        `Unsupported language "${options.languageOverride}". Use one of: typescript, javascript, python.`
      );
    }
    answers.language = override;
  }

  if (!options.interactive) return answers;

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const prompter = new Prompter(rl);
  try {
    if (detected) {
      console.log(`  Detected a mostly ${detected} project.\n`);
    } else {
      console.log('  Could not detect the project language from its files.\n');
    }

    if (!options.languageOverride) {
      answers.language = await askChoice(
        prompter,
        'Primary language',
        [
          { key: '1', label: 'typescript', value: 'typescript' as InitLanguage },
          { key: '2', label: 'javascript', value: 'javascript' as InitLanguage },
          { key: '3', label: 'python', value: 'python' as InitLanguage },
        ],
        answers.language
      );
    }

    answers.preset = await askChoice(
      prompter,
      'How hard should Buggy search for bugs?',
      [
        { key: '1', label: 'quick     (30 inputs — fast feedback)', value: SEARCH_PRESETS.quick },
        { key: '2', label: 'balanced  (100 inputs — recommended)', value: SEARCH_PRESETS.balanced },
        { key: '3', label: 'thorough  (300 inputs — slower, finds more)', value: SEARCH_PRESETS.thorough },
      ],
      answers.preset,
      (v) => v.name
    );

    answers.timeoutSeconds = await askNumber(
      prompter,
      'Max seconds a single function may run',
      answers.timeoutSeconds,
      1,
      300
    );

    answers.watchlistScope = await askChoice(
      prompter,
      'Share what Buggy learns?',
      [
        { key: '1', label: 'local    (private to you)', value: 'local' as const },
        { key: '2', label: 'team     (commit lessons for teammates)', value: 'team' as const },
        { key: '3', label: 'global   (reuse across your projects)', value: 'global' as const },
        { key: '4', label: 'layered  (all of the above — recommended)', value: 'layered' as const },
      ],
      answers.watchlistScope
    );

    answers.updateGitignore = await askYesNo(
      prompter,
      'Add .debugger/ to .gitignore?',
      answers.updateGitignore
    );
  } finally {
    rl.close();
  }

  return answers;
}

/**
 * Prompt reader that degrades gracefully when input ends.
 *
 * `readline.question()` returns a promise that never settles if stdin closes
 * (Ctrl+D, a closed pipe, a truncated script). Racing each question against the
 * interface's `close` event means the wizard falls back to defaults instead of
 * hanging the CLI forever.
 */
class Prompter {
  private lines: AsyncIterator<string>;
  private output: { write(chunk: string): unknown };
  private ended = false;

  /**
   * @param rl - Readline interface over the input stream.
   * @param output - Stream the prompt text is written to.
   */
  constructor(
    rl: ReturnType<typeof createInterface>,
    output: { write(chunk: string): unknown } = process.stdout
  ) {
    // Consuming lines through the async iterator (rather than rl.question) keeps
    // already-buffered lines available after the underlying stream ends, and
    // signals EOF via `done` instead of leaving a promise forever pending.
    this.lines = rl[Symbol.asyncIterator]();
    this.output = output;
  }

  /** True once input has ended, so remaining questions should use defaults. */
  get inputEnded(): boolean {
    return this.ended;
  }

  /**
   * Ask a question.
   *
   * @returns The trimmed reply, or null when input has ended.
   */
  async ask(prompt: string): Promise<string | null> {
    if (this.ended) return null;

    this.output.write(prompt);
    const next = await this.lines.next();
    if (next.done) {
      this.ended = true;
      this.output.write('\n');
      return null;
    }
    return next.value.trim();
  }
}

/** Ask the user to pick from a numbered list. */
async function askChoice<T>(
  prompter: Prompter,
  question: string,
  choices: { key: string; label: string; value: T }[],
  defaultValue: T,
  describe: (value: T) => string = (v) => String(v)
): Promise<T> {
  const defaultLabel = describe(defaultValue);
  if (prompter.inputEnded) return defaultValue;

  console.log(`${question}`);
  for (const choice of choices) {
    const isDefault = describe(choice.value) === defaultLabel;
    console.log(`    ${choice.key}) ${choice.label}${isDefault ? '  [default]' : ''}`);
  }

  const reply = await prompter.ask('  > ');
  console.log('');
  if (reply === null || reply === '') return defaultValue;

  const byKey = choices.find((c) => c.key === reply);
  if (byKey) return byKey.value;

  const byLabel = choices.find(
    (c) => c.label.toLowerCase().startsWith(reply.toLowerCase())
  );
  if (byLabel) return byLabel.value;

  console.log(`  Unrecognized choice "${reply}" — using ${defaultLabel}.\n`);
  return defaultValue;
}

/** Ask for a number within an inclusive range. */
async function askNumber(
  prompter: Prompter,
  question: string,
  defaultValue: number,
  min: number,
  max: number
): Promise<number> {
  const reply = await prompter.ask(`${question} [${defaultValue}]: `);
  console.log('');
  if (reply === null || reply === '') return defaultValue;

  const parsed = Number(reply);
  if (!Number.isInteger(parsed) || parsed < min || parsed > max) {
    console.log(`  "${reply}" is not an integer in ${min}-${max} — using ${defaultValue}.\n`);
    return defaultValue;
  }
  return parsed;
}

/** Ask a yes/no question. */
async function askYesNo(
  prompter: Prompter,
  question: string,
  defaultValue: boolean
): Promise<boolean> {
  const hint = defaultValue ? 'Y/n' : 'y/N';
  const reply = await prompter.ask(`${question} [${hint}]: `);
  console.log('');
  if (reply === null || reply === '') return defaultValue;
  const normalized = reply.toLowerCase();
  return normalized === 'y' || normalized === 'yes';
}

/**
 * Ensure `.debugger/` is ignored by git.
 *
 * @param projectRoot - Project directory containing (or needing) a .gitignore.
 * @returns What action was taken, for reporting.
 */
export function ensureGitignore(projectRoot: string): 'added' | 'already-present' | 'created' {
  const path = join(projectRoot, '.gitignore');
  const entry = '.debugger/';

  if (!existsSync(path)) {
    writeFileSync(path, `# Buggy working directory\n${entry}\n`, 'utf-8');
    return 'created';
  }

  const current = readFileSync(path, 'utf-8');
  const alreadyListed = current
    .split(/\r?\n/)
    .some((line) => line.trim().replace(/\/$/, '') === '.debugger');
  if (alreadyListed) return 'already-present';

  const prefix = current.endsWith('\n') ? '' : '\n';
  appendFileSync(path, `${prefix}\n# Buggy working directory\n${entry}\n`, 'utf-8');
  return 'added';
}

/**
 * Report whether the interpreter needed to prove bugs in this language is
 * available, so a misconfigured environment surfaces at init rather than midway
 * through the first investigation.
 *
 * @param language - The configured language.
 * @returns A warning message, or null when the runtime looks usable.
 */
export function checkRuntimeAvailable(language: InitLanguage): string | null {
  if (language !== 'python') return null;

  const command = process.env.BUGGY_PYTHON || (process.platform === 'win32' ? 'python' : 'python3');
  return `Bug proving runs your functions in "${command}". Make sure it is on PATH (override with the BUGGY_PYTHON environment variable).`;
}
