#!/usr/bin/env node
/**
 * Buggy CLI
 *
 * Command-line interface for running the proof-carrying debugger
 * against any target project.
 *
 * Usage:
 *   buggy init
 *   buggy analyze <file>
 *   buggy investigate <function> --file <path>
 *   buggy status <id>
 *   buggy halt <id>
 */

import { parseArgs } from 'node:util';
import { resolve, extname } from 'node:path';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { loadConfig, ConfigError } from './config/config-loader.js';
import { initializeDatabase } from './database/graph-db.js';
import { ProofDebugger } from './api.js';
import type { InvestigationReport, InvestigationStatus } from './types/orchestrator.js';
import type { ParseResult } from './types/cst.js';

// ─── Color Helpers ───────────────────────────────────────────────────────────

const NO_COLOR = !!(process.env['NO_COLOR'] || process.env['TERM'] === 'dumb');

const colors = {
  reset: NO_COLOR ? '' : '\x1b[0m',
  bold: NO_COLOR ? '' : '\x1b[1m',
  dim: NO_COLOR ? '' : '\x1b[2m',
  red: NO_COLOR ? '' : '\x1b[31m',
  green: NO_COLOR ? '' : '\x1b[32m',
  yellow: NO_COLOR ? '' : '\x1b[33m',
  blue: NO_COLOR ? '' : '\x1b[34m',
  cyan: NO_COLOR ? '' : '\x1b[36m',
  magenta: NO_COLOR ? '' : '\x1b[35m',
};

function colorize(color: keyof typeof colors, text: string): string {
  return `${colors[color]}${text}${colors.reset}`;
}

// ─── Progress Indicator ──────────────────────────────────────────────────────

class Spinner {
  private frames = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
  private interval: ReturnType<typeof setInterval> | null = null;
  private frameIndex = 0;

  start(message: string): void {
    if (NO_COLOR || !process.stdout.isTTY) {
      process.stdout.write(`${message}...\n`);
      return;
    }
    this.frameIndex = 0;
    this.interval = setInterval(() => {
      const frame = this.frames[this.frameIndex % this.frames.length];
      process.stdout.write(`\r${colorize('cyan', frame)} ${message}`);
      this.frameIndex++;
    }, 80);
  }

  stop(message?: string): void {
    if (this.interval) {
      clearInterval(this.interval);
      this.interval = null;
      process.stdout.write('\r\x1b[K');
    }
    if (message) {
      process.stdout.write(`${message}\n`);
    }
  }
}

// ─── CLI Config ──────────────────────────────────────────────────────────────

interface CliFlags {
  json: boolean;
  verbose: boolean;
  file?: string;
  help: boolean;
}

function parseCliArgs(): { command: string; args: string[]; flags: CliFlags } {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      json: { type: 'boolean', default: false },
      verbose: { type: 'boolean', default: false },
      file: { type: 'string', short: 'f' },
      help: { type: 'boolean', default: false, short: 'h' },
    },
  });

  const command = positionals[0] ?? '';
  const args = positionals.slice(1);

  return {
    command,
    args,
    flags: {
      json: values.json ?? false,
      verbose: values.verbose ?? false,
      file: values.file,
      help: values.help ?? false,
    },
  };
}

// ─── Commands ────────────────────────────────────────────────────────────────

function printUsage(): void {
  console.log(`
${colorize('bold', 'buggy')} — Proof-Carrying Program Repair and Debugging System

${colorize('bold', 'USAGE:')}
  buggy <command> [options]

${colorize('bold', 'COMMANDS:')}
  init                              Create a .debugger.yaml template in the current directory
  analyze <file>                    Parse a file and show the semantic graph
  investigate <function> --file <path>  Run full investigation pipeline on a function
  status <id>                       Show status of a running investigation
  halt <id>                         Halt a running investigation

${colorize('bold', 'OPTIONS:')}
  --json        Output results as JSON (machine-readable)
  --verbose     Enable detailed logging
  --file, -f    Specify the target file (for investigate command)
  --help, -h    Show this help message

${colorize('bold', 'EXAMPLES:')}
  buggy init
  buggy analyze src/payments.ts
  buggy investigate processPayment --file src/payments.ts
  buggy investigate processPayment -f src/payments.ts --json
`);
}

const TEMPLATE_YAML = `# Buggy Configuration
# Generated by: buggy init
version: "1.0"

language: typescript

parser:
  command: tree-sitter-typescript
  # grammar_path: ./path/to/custom-grammar.wasm

lsp:
  command: typescript-language-server
  # args: ["--stdio"]
  # initialization_options: {}

sandbox:
  runtime: node
  memory_limit_mb: 512
  timeout_seconds: 60
  egress_policy: deny

oracles:
  timeout_threshold_seconds: 10
  crash_detection: true
  overflow_detection: true
  determinism_check_count: 5

probe:
  search_budget: 100
  max_refinement_iterations: 10

# plugs:
#   parsing: ./plugs/my-parser
#   oracles: ["./plugs/custom-oracle"]
#   repair: ./plugs/my-repair-strategy
#   sandbox_executor: ./plugs/my-sandbox
`;

async function commandInit(flags: CliFlags): Promise<void> {
  const targetPath = resolve(process.cwd(), '.debugger.yaml');

  if (existsSync(targetPath)) {
    if (flags.json) {
      console.log(JSON.stringify({ error: '.debugger.yaml already exists' }));
    } else {
      console.log(colorize('yellow', '⚠') + ' .debugger.yaml already exists in this directory.');
      console.log('  Remove it first if you want to regenerate.');
    }
    process.exitCode = 1;
    return;
  }

  writeFileSync(targetPath, TEMPLATE_YAML, 'utf-8');

  // Also create .debugger/ directory
  const debuggerDir = resolve(process.cwd(), '.debugger');
  if (!existsSync(debuggerDir)) {
    mkdirSync(debuggerDir, { recursive: true });
  }

  if (flags.json) {
    console.log(JSON.stringify({ created: ['.debugger.yaml', '.debugger/'] }));
  } else {
    console.log(colorize('green', '✓') + ' Created .debugger.yaml');
    console.log(colorize('green', '✓') + ' Created .debugger/ directory');
    console.log('');
    console.log('  Edit .debugger.yaml to configure the debugger for your project.');
    console.log('  Then run: ' + colorize('cyan', 'buggy analyze <file>'));
  }
}

async function commandAnalyze(args: string[], flags: CliFlags): Promise<void> {
  const filePath = args[0];
  if (!filePath) {
    console.error(colorize('red', 'Error:') + ' Missing file path argument.');
    console.error('  Usage: buggy analyze <file>');
    process.exitCode = 1;
    return;
  }

  const resolvedPath = resolve(process.cwd(), filePath);
  if (!existsSync(resolvedPath)) {
    console.error(colorize('red', 'Error:') + ` File not found: ${resolvedPath}`);
    process.exitCode = 1;
    return;
  }

  const spinner = new Spinner();
  const debugger_ = new ProofDebugger({ projectRoot: process.cwd() });

  try {
    if (!flags.json) {
      spinner.start('Initializing debugger');
    }
    await debugger_.initialize();
    if (!flags.json) {
      spinner.stop(colorize('green', '✓') + ' Debugger initialized');
    }

    if (!flags.json) {
      spinner.start(`Parsing ${filePath}`);
    }
    const result = await debugger_.parse(resolvedPath);
    if (!flags.json) {
      spinner.stop(colorize('green', '✓') + ` Parsed ${filePath}`);
    }

    if (flags.json) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      printParseResult(result, flags.verbose);
    }
  } catch (err) {
    spinner.stop();
    handleError(err, flags);
  } finally {
    await debugger_.shutdown();
  }
}

async function commandInvestigate(args: string[], flags: CliFlags): Promise<void> {
  const functionId = args[0];
  if (!functionId) {
    console.error(colorize('red', 'Error:') + ' Missing function name argument.');
    console.error('  Usage: buggy investigate <function> --file <path>');
    process.exitCode = 1;
    return;
  }

  const filePath = flags.file;
  if (!filePath) {
    console.error(colorize('red', 'Error:') + ' Missing --file flag.');
    console.error('  Usage: buggy investigate <function> --file <path>');
    process.exitCode = 1;
    return;
  }

  const resolvedPath = resolve(process.cwd(), filePath);
  if (!existsSync(resolvedPath)) {
    console.error(colorize('red', 'Error:') + ` File not found: ${resolvedPath}`);
    process.exitCode = 1;
    return;
  }

  const spinner = new Spinner();
  const debugger_ = new ProofDebugger({ projectRoot: process.cwd() });

  try {
    if (!flags.json) {
      spinner.start('Initializing debugger');
    }
    await debugger_.initialize();
    if (!flags.json) {
      spinner.stop(colorize('green', '✓') + ' Debugger initialized');
    }

    if (!flags.json) {
      spinner.start(`Investigating ${functionId} in ${filePath}`);
    }

    const report = await debugger_.investigate({
      functionId,
      filePath: resolvedPath,
    });

    if (!flags.json) {
      spinner.stop(colorize('green', '✓') + ' Investigation complete');
    }

    if (flags.json) {
      console.log(JSON.stringify(report, null, 2));
    } else {
      printReport(report, flags.verbose);
    }
  } catch (err) {
    spinner.stop();
    handleError(err, flags);
  } finally {
    await debugger_.shutdown();
  }
}

async function commandStatus(args: string[], flags: CliFlags): Promise<void> {
  const id = args[0];
  if (!id) {
    console.error(colorize('red', 'Error:') + ' Missing investigation ID.');
    console.error('  Usage: buggy status <id>');
    process.exitCode = 1;
    return;
  }

  const debugger_ = new ProofDebugger({ projectRoot: process.cwd() });

  try {
    await debugger_.initialize();
    const status = debugger_.getStatus(id);

    if (!status) {
      if (flags.json) {
        console.log(JSON.stringify({ error: 'Investigation not found', id }));
      } else {
        console.error(colorize('yellow', '⚠') + ` No investigation found with ID: ${id}`);
      }
      process.exitCode = 1;
      return;
    }

    if (flags.json) {
      console.log(JSON.stringify(status, null, 2));
    } else {
      printStatus(status);
    }
  } catch (err) {
    handleError(err, flags);
  } finally {
    await debugger_.shutdown();
  }
}

async function commandHalt(args: string[], flags: CliFlags): Promise<void> {
  const id = args[0];
  if (!id) {
    console.error(colorize('red', 'Error:') + ' Missing investigation ID.');
    console.error('  Usage: buggy halt <id>');
    process.exitCode = 1;
    return;
  }

  const debugger_ = new ProofDebugger({ projectRoot: process.cwd() });

  try {
    await debugger_.initialize();
    debugger_.halt(id);

    if (flags.json) {
      console.log(JSON.stringify({ halted: true, id }));
    } else {
      console.log(colorize('green', '✓') + ` Investigation ${id} halted.`);
    }
  } catch (err) {
    handleError(err, flags);
  } finally {
    await debugger_.shutdown();
  }
}

// ─── Output Formatters ───────────────────────────────────────────────────────

function printParseResult(result: ParseResult, verbose: boolean): void {
  console.log('');
  console.log(colorize('bold', '  Parse Result'));
  console.log(colorize('dim', '  ─────────────────────────────────────'));
  console.log(`  File:       ${result.file_path}`);
  console.log(`  Duration:   ${result.duration_ms.toFixed(2)}ms`);
  console.log(`  Errors:     ${result.errors.length === 0 ? colorize('green', '0') : colorize('red', String(result.errors.length))}`);
  console.log(`  Root type:  ${result.cst.type}`);
  console.log(`  Node count: ${countNodes(result.cst)}`);

  if (result.errors.length > 0) {
    console.log('');
    console.log(colorize('bold', '  Syntax Errors:'));
    for (const err of result.errors) {
      console.log(`    ${colorize('red', '•')} ${err.message} (${err.location.row}:${err.location.column})`);
    }
  }

  if (verbose) {
    console.log('');
    console.log(colorize('bold', '  CST Summary (depth 2):'));
    printCstSummary(result.cst, 2, '    ');
  }

  console.log('');
}

function printCstSummary(node: ParseResult['cst'], maxDepth: number, indent: string): void {
  if (maxDepth <= 0) return;
  for (const child of node.children.slice(0, 20)) {
    const errorMarker = child.is_error ? colorize('red', ' [ERROR]') : '';
    console.log(`${indent}${colorize('dim', child.type)}${errorMarker} (${child.start_position.row}:${child.start_position.column})`);
    printCstSummary(child, maxDepth - 1, indent + '  ');
  }
  if (node.children.length > 20) {
    console.log(`${indent}${colorize('dim', `... and ${node.children.length - 20} more`)}`);
  }
}

function printReport(report: InvestigationReport, verbose: boolean): void {
  console.log('');
  console.log(colorize('bold', '  Investigation Report'));
  console.log(colorize('dim', '  ─────────────────────────────────────'));
  console.log(`  ID:     ${report.id}`);

  const statusColor = report.status === 'confirmed_and_repaired' ? 'green'
    : report.status === 'unconfirmed' ? 'yellow'
    : report.status === 'halted' ? 'red'
    : 'magenta';
  console.log(`  Status: ${colorize(statusColor, report.status)}`);

  if (report.proof) {
    console.log('');
    console.log(colorize('bold', '  Proof-of-Failure Certificate:'));
    console.log(`    Violated:    ${report.proof.violated_postcondition}`);
    console.log(`    Input:       ${JSON.stringify(report.proof.test_input)}`);
    console.log(`    Output:      ${JSON.stringify(report.proof.observed_output)}`);
    console.log(`    Admissible:  ${report.proof.admissibility_verified_at}`);
    console.log(`    Sound:       ${report.proof.soundness_verified_at}`);
    console.log(`    Unique:      ${report.proof.uniqueness_verified_at}`);
  }

  if (report.approved_patches.length > 0) {
    console.log('');
    console.log(colorize('bold', `  Approved Patches (${report.approved_patches.length}):`));
    for (const { patch, classification } of report.approved_patches) {
      console.log(`    ${colorize('green', '✓')} ${patch.id} — overfitting: ${((classification.overfitting_probability ?? 0) * 100).toFixed(1)}%`);
      if (verbose) {
        console.log(`      File: ${patch.target_file} (L${patch.target_range.start_line}-${patch.target_range.end_line})`);
        console.log(`      Diff:\n${indentLines(patch.diff, '        ')}`);
      }
    }
  }

  if (report.rejected_patches.length > 0 && verbose) {
    console.log('');
    console.log(colorize('bold', `  Rejected Patches (${report.rejected_patches.length}):`));
    for (const { patch, rejection_reason } of report.rejected_patches) {
      console.log(`    ${colorize('red', '✗')} ${patch.id} — ${rejection_reason}`);
    }
  }

  if (report.timeline.length > 0) {
    console.log('');
    console.log(colorize('bold', '  Timeline:'));
    for (const phase of report.timeline) {
      console.log(`    ${colorize('dim', phase.phase.padEnd(15))} ${phase.agent} (${phase.started_at} → ${phase.completed_at})`);
    }
  }

  console.log('');
}

function printStatus(status: InvestigationStatus): void {
  console.log('');
  console.log(colorize('bold', '  Investigation Status'));
  console.log(colorize('dim', '  ─────────────────────────────────────'));
  console.log(`  ID:       ${status.id}`);
  console.log(`  Phase:    ${status.phase}`);
  console.log(`  Agent:    ${status.current_agent}`);
  console.log(`  Elapsed:  ${status.elapsed_ms}ms`);
  console.log(`  Started:  ${status.started_at}`);

  const ir = status.intermediate_results;
  if (Object.keys(ir).length > 0) {
    console.log('');
    console.log(colorize('bold', '  Intermediate Results:'));
    if (ir.cst_nodes_parsed != null) console.log(`    CST nodes parsed:       ${ir.cst_nodes_parsed}`);
    if (ir.symbols_resolved != null) console.log(`    Symbols resolved:       ${ir.symbols_resolved}`);
    if (ir.specifications_refined != null) console.log(`    Specs refined:          ${ir.specifications_refined}`);
    if (ir.probe_iterations != null) console.log(`    PROBE iterations:       ${ir.probe_iterations}`);
    if (ir.fuzz_mutations != null) console.log(`    Fuzz mutations:         ${ir.fuzz_mutations}`);
    if (ir.patches_generated != null) console.log(`    Patches generated:      ${ir.patches_generated}`);
    if (ir.patches_approved != null) console.log(`    Patches approved:       ${ir.patches_approved}`);
  }

  console.log('');
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function countNodes(node: ParseResult['cst']): number {
  let count = 1;
  for (const child of node.children) {
    count += countNodes(child);
  }
  return count;
}

function indentLines(text: string, indent: string): string {
  return text.split('\n').map(line => `${indent}${line}`).join('\n');
}

function handleError(err: unknown, flags: CliFlags): void {
  if (err instanceof ConfigError) {
    if (flags.json) {
      console.log(JSON.stringify({ error: err.message, type: 'ConfigError' }));
    } else {
      console.error(colorize('red', 'Configuration Error:') + ` ${err.message}`);
      console.error('  Run ' + colorize('cyan', 'buggy init') + ' to create a configuration file.');
    }
  } else if (err instanceof Error) {
    if (flags.json) {
      console.log(JSON.stringify({ error: err.message, type: err.name }));
    } else {
      console.error(colorize('red', 'Error:') + ` ${err.message}`);
      if (flags.verbose && err.stack) {
        console.error(colorize('dim', err.stack));
      }
    }
  } else {
    console.error(colorize('red', 'Error:') + ` ${String(err)}`);
  }
  process.exitCode = 1;
}

// ─── Language Detection ──────────────────────────────────────────────────────

/** Auto-detect language from file extension. */
export function detectLanguage(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  const languageMap: Record<string, string> = {
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'javascript',
    '.jsx': 'javascript',
    '.py': 'python',
    '.rs': 'rust',
    '.go': 'go',
    '.java': 'java',
    '.c': 'c',
    '.cpp': 'cpp',
    '.h': 'c',
    '.hpp': 'cpp',
  };
  return languageMap[ext] ?? 'unknown';
}

// ─── Main Entry Point ────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const { command, args, flags } = parseCliArgs();

  if (flags.help || !command) {
    printUsage();
    return;
  }

  switch (command) {
    case 'init':
      await commandInit(flags);
      break;
    case 'analyze':
      await commandAnalyze(args, flags);
      break;
    case 'investigate':
      await commandInvestigate(args, flags);
      break;
    case 'status':
      await commandStatus(args, flags);
      break;
    case 'halt':
      await commandHalt(args, flags);
      break;
    default:
      console.error(colorize('red', 'Error:') + ` Unknown command "${command}"`);
      console.error('  Run ' + colorize('cyan', 'buggy --help') + ' for usage.');
      process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exitCode = 1;
});
